-- CONFIGURAÇÃO DO BANCO PARA O SITE DÉBORA APARECIDA NAIL DESIGN
-- Execute este script no SQL Editor do Supabase depois de criar as tabelas pelo Table Editor.
-- Ele NÃO apaga os dados existentes.

-- 1) Perfil de cliente: marca quem é administradora do sistema.
alter table public.clientes add column if not exists is_admin boolean not null default false;

-- Garante que o id numérico das tabelas criadas no Table Editor seja automático.
do $$
begin
  if not exists (
    select 1
    from pg_attribute a
    join pg_class c on c.oid = a.attrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'clientes'
      and a.attname = 'id'
      and a.attidentity <> ''
  ) then
    execute 'alter table public.clientes alter column id add generated by default as identity';
  end if;
end $$;

-- 2) Liga a conta do Supabase Auth ao cadastro da cliente.
alter table public.clientes
  drop constraint if exists clientes_user_id_fkey;
alter table public.clientes
  add constraint clientes_user_id_fkey
  foreign key (user_id) references auth.users(id) on delete cascade;

-- 3) Evita dois cadastros com o mesmo e-mail no perfil.
create unique index if not exists clientes_email_unique_idx
  on public.clientes (lower(email));

-- 4) Evita dois horários iguais no mesmo dia.
create unique index if not exists horarios_data_horario_unique_idx
  on public.horarios (data, horario);

-- 5) Evita dois agendamentos no mesmo dia e horário.
create unique index if not exists agendamentos_data_horario_unique_idx
  on public.agendamentos (data, horario);

-- 6) Função segura para checar se a pessoa logada é administradora.
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.clientes
    where user_id = auth.uid() and is_admin = true
  );
$$;

-- 7) Função segura para checar se um registro de cliente pertence à conta logada.
create or replace function public.owns_client(p_cliente_id bigint)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.clientes
    where id = p_cliente_id and user_id = auth.uid()
  );
$$;

-- 8) RLS
alter table public.clientes enable row level security;
alter table public.agendamentos enable row level security;
alter table public.vip_fidelidade enable row level security;
alter table public.horarios enable row level security;

-- Clientes
 drop policy if exists clientes_select_own on public.clientes;
 drop policy if exists clientes_insert_own on public.clientes;
 drop policy if exists clientes_update_own on public.clientes;
 drop policy if exists clientes_admin_all on public.clientes;
create policy clientes_select_own on public.clientes
for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy clientes_insert_own on public.clientes
for insert to authenticated with check (user_id = auth.uid());
create policy clientes_update_own on public.clientes
for update to authenticated using (user_id = auth.uid() or public.is_admin())
with check (user_id = auth.uid() or public.is_admin());
create policy clientes_admin_all on public.clientes
for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Agendamentos
 drop policy if exists agendamentos_select_own on public.agendamentos;
 drop policy if exists agendamentos_insert_own on public.agendamentos;
 drop policy if exists agendamentos_admin_all on public.agendamentos;
create policy agendamentos_select_own on public.agendamentos
for select to authenticated
using (public.owns_client(cliente_id) or public.is_admin());
create policy agendamentos_insert_own on public.agendamentos
for insert to authenticated
with check (public.owns_client(cliente_id));
create policy agendamentos_admin_all on public.agendamentos
for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- VIP: cliente vê apenas o próprio cartão; administradora vê tudo.
 drop policy if exists vip_select_own on public.vip_fidelidade;
 drop policy if exists vip_admin_all on public.vip_fidelidade;
create policy vip_select_own on public.vip_fidelidade
for select to authenticated
using (public.owns_client(cliente_id) or public.is_admin());
create policy vip_admin_all on public.vip_fidelidade
for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Horários: clientes autenticadas podem consultar horários disponíveis; só admin altera.
 drop policy if exists horarios_select_available on public.horarios;
 drop policy if exists horarios_admin_all on public.horarios;
create policy horarios_select_available on public.horarios
for select to authenticated using (disponivel = true or public.is_admin());
create policy horarios_admin_all on public.horarios
for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- 9) Realtime não é obrigatório para o primeiro lançamento.
-- Pode ser ativado depois, se quisermos notificações em tempo real.

-- 10) Uma ficha VIP por cliente.
create unique index if not exists vip_fidelidade_cliente_unique_idx
  on public.vip_fidelidade (cliente_id);
